version: 2.1
orbs:
  python: circleci/python@2.0.1
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          command: |
            python -m unittest TestTriangle

      - store_test_results:
          path: test-results

workflows:
  testing_triangles:
    jobs:
      - build-and-test